[package]
name = "rfcs"
version = "0.1.0"
authors = ["Matthias Endler <matthias-endler@gmx.net>"]
edition = "2018"

[dependencies]
hubcaps = "0.5.0"
futures = "0.1.25"
tokio = "0.1.13"
pretty_env_logger = "0.3.0"
failure = "0.1.5"
hyper-tls = "0.3.1"
hyper = "0.12.19"
